### ISSUE TITLE
cannot generate a sitemap of https://www.ethz.ch/en.html

### ISSUE THREAD

**Issue by mkantautas** [lgraubner/sitemap-generator#42]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
```
(node:19773) UnhandledPromiseRejectionWarning: NestedError: Cannot write to `path`: EISDIR: illegal operation on a directory, open 'path'
    at WriteStream.write.on.err (path/node_modules/cp-file/index.js:38:12)
    at emitOne (events.js:121:20)
    at WriteStream.emit (events.js:211:7)
    at path/node_modules/graceful-fs/graceful-fs.js:211:14
    at path/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:135:15)
Caused By: Error: EISDIR: illegal operation on a directory, open 'path'
(node:19773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19773) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```
**If the current behavior is a bug, please provide the steps to reproduce.**
Try to generate a sitemap of this webpage

**What is the expected behavior?**
Should successfully generate a sitemap

**Comment by Rob-Rychs** [comment]
hmm have you tried running it without specifying: /en.html at end of url?

**Comment by lgraubner** [comment]
Can not reproduce

Closed due to inactivity.
