### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by mgifford** [lgraubner/sitemap-generator#83]
On a Mac I downloaded the sitemap-generator then ran 

```
$ npm install -S sitemap-generator
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "sitemap-generator" under a package
npm ERR! also called "sitemap-generator". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mikegifford/.npm/_logs/2020-09-09T14_28_34_007Z-debug.log
```

Not sure you need all of the saveTree

```
$ cat  /Users/mikegifford/.npm/_logs/2020-09-09T14_28_34_007Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-S',
1 verbose cli   'sitemap-generator' ]
2 info using npm@6.14.8
3 info using node@v10.13.0
4 verbose npm-session fe9c9a7b16e625d8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/sitemap-generator 875ms
8 http fetch GET 200 https://registry.npmjs.org/sitemap-generator/-/sitemap-generator-8.5.0.tgz 458ms
9 silly pacote tag manifest for sitemap-generator@latest fetched in 1371ms
10 timing stage:loadCurrentTree Completed in 1485ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1002ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:rollbackFailedOptional Completed in 1ms
18 timing stage:runTopLevelLifecycles Completed in 2492ms
19 silly saveTree sitemap-generator@0.0.0-semantically-released
19 silly saveTree ├─┬ async@2.6.1
19 silly saveTree │ └── lodash@4.17.15
19 silly saveTree ├─┬ cheerio@1.0.0-rc.2


...

19 silly saveTree └─┬ url-parse@1.4.7
19 silly saveTree   ├── querystringify@2.1.1
19 silly saveTree   └── requires-port@1.0.0
20 verbose stack Error: Refusing to install package with name "sitemap-generator" under a package
20 verbose stack also called "sitemap-generator". Did you name your project the same
20 verbose stack as the dependency you're installing?
20 verbose stack
20 verbose stack For more information, see:
20 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
20 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:75:14)
20 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
20 verbose stack     at hasMinimumFields (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:30:12)
20 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
20 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
20 verbose stack     at Array.forEach (<anonymous>)
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
20 verbose stack     at Array.forEach (<anonymous>)
20 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
20 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:3)
20 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
21 verbose cwd /Users/mikegifford/sitemap-generator
22 verbose Darwin 19.6.0
23 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-S" "sitemap-generator"
24 verbose node v10.13.0
25 verbose npm  v6.14.8
26 error code ENOSELF
27 error Refusing to install package with name "sitemap-generator" under a package
27 error also called "sitemap-generator". Did you name your project the same
27 error as the dependency you're installing?
27 error
27 error For more information, see:
27 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
28 verbose exit [ 1, true ]
```

Maybe I have another sitemap-generator somewhere....

**Comment by lgraubner** [comment]
This is a NPM problem. What is the name in your `package.json`? Looks like it's sitemap-generator as well and that doesn't work.
